### ISSUE TITLE
Wrong projection

### ISSUE THREAD

**Issue by pcav** [geodrinx/smartroadsense#2]
The data are loaded as EPSG:4326, even though they are (presumably 32632).

**Comment by geodrinx** [comment]
You wrong.   :)

They are Lat Long GPS based.   This is the start of CSV file:

"LATITUDE","LONGITUDE","PPE","OSM_ID","HIGHWAY","UPDATED_AT"
44.4879819341,11.276569064137,0.017857962446983,28614974,trunk,2015-02-28 00:48:45.120542

**Comment by pcav** [comment]
Well, they end up in the wrong position in my QGIS canvas anyway.

**Comment by geodrinx** [comment]
Do you have "on the fly" projection setting active ?

**Comment by pcav** [comment]
Redone from scratch, it works - sorry for the noise.
